services:
  - type: web
    name: key-scanner
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GITHUB_TOKEN
        sync: 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
      - key: DISCORD_WEBHOOK
        sync: https://discord.com/api/webhooks/1520868032988053544/CK7GcmEE28Z8Ex8A9750iIh9TwZ_9kDoXbaK0O8yKj2N30RmNiYIXdlEht2at4TG6fNq
      - key: MONGODB_URI
        sync: mongodb+srv://ehcjgdiry09_db_user:8Z4GvTJmWwnkZcpV@cluster0.9zbutan.mongodb.net/?appName=Cluster0
      - key: ENABLE_VERIFY
        value: "true"
      - key: VERIFY_WORKERS
        value: "20"
      - key: VERIFY_TIMEOUT
        value: "15"
      - key: RENDER
        value: "true"
      - key: PORT
        value: "10000"
