name: Deploy to Bunny Edge Scripting

on:
  push:
    branches:
      - main 

# This is the new section you need to add to fix the error
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Script to Bunny Edge Scripting
        uses: BunnyWay/actions/deploy-script@main
        with:
          script_id: 80334
          file: "script.ts"
